### PR TITLE
chore(ci): re-enable `deny` via `RUSTFLAGS`

### PR DESCRIPTION
**Pull request by grtlr**

### CODE REVIEW

**Comment by grtlr** [comment]
This can't be merged until the dependencies, namely `petgraph` and `indexmap` are updated.

**Review by Alex6323 — DISMISSED** [review]

**Comment by workingjubilee** [comment]
This is not an issue with the indexmap or petgraph crates per se,
so you may be waiting a long time if you expect them to fix this.
I recommend familiarizing yourself with these discussions:
https://github.com/bluss/indexmap/issues?q=is%3Aissue+arguments

**Comment by grtlr** [comment]
@workingjubilee Thank you very much for your help! This is a very confusing situation.

**Comment by workingjubilee** [comment]
This may require a `[patch.crates-io]` override instead.

**Comment by grtlr** [comment]
Thank you so much, will try it out!

**Comment by grtlr** [comment]
Ah, also does not work:

```
warning: patch for `indexmap` uses the features mechanism. default-features and features will not take effect because the patch dependency does not support this mechanism
```

**Comment by workingjubilee** [comment]
Oh right. Bother. Tedious...

**Comment by grtlr** [comment]
All good, thank you so much anyway for taking the time respond and think about this!

**Comment by grtlr** [comment]
I'm closing this for now, maybe these things will settle in the future.

**Pull request closed without merging**
