### PR TITLE
quick demo

### PR DESCRIPTION
**Pull request by grtlr**
just one suggestion

### CODE REVIEW

**Comment by Alexandcoats** [comment]
What about the other function that uses identical documents?

**Comment by Alexandcoats** [comment]
Yes, but then things start to really get unclean.

**Comment by grtlr** [comment]
I'd argue against that. You could even write test cases for those individual functions.

**Comment by Alexandcoats** [comment]
There are two problems with that:
1. We will end up with lots of free-floating functions that just generate *part* of a query and make no sense out of context. Naming them will be an issue too.
2. Separating the query into many pieces obfuscates it and makes it difficult to reason about.

**Comment by grtlr** [comment]
Hmm, ideally we would have something like a query builder for many of those things. Of course that would increase the overall code, but then things could become a lot more flexible and documented compared to free functions and raw queries.

**Comment by Alexandcoats** [comment]
Yes, I agree on both counts. And I think that is too far outside the scope of the PR, which is why I did not attempt it.

**Comment by Alex6323** [comment]
I lean towards @Alexandcoats here. Moving parts of the query into functions doesn't really help here. It has the disadvantages that Alex already stated. The correctness of the queries should always be guaranteed by tests. If our test suite doesn't catch that divergence you mentioned, Jochen, then that's a bug in our test suite (we missed to write a necessary test case).
Moreover, I really prefer the atomicity of our current queries meaning that all I need to read about a particular query is in one place and I don't have to jump back and forth.

**Pull request closed without merging**
